### ISSUE TITLE
It looks like the version is wrong in the marketplace

### ISSUE THREAD

**Issue by werto87** [VaultVulp/gp-docker-action#10]
In the marketplace there is this code to copy and paste which claims to use "GitHub Packages" but it uses the old "GitHub docker".
When I change "VaultVulp/gp-docker-action@1.1.8" into "VaultVulp/gp-docker-action@1.2.0" everything works.
So I think you need to update the "template".

**Comment by VaultVulp** [comment]
Thanks for noticing, @werto87 !
I bumped the version at the Marketpace, hope this helps.

**Comment by werto87** [comment]
Looks good. Thanks!
