### ISSUE TITLE
publisher user

### ISSUE THREAD

**Issue by manang** [VaultVulp/gp-docker-action#18]
question:
is publisher user a special user to publish stuff of github?
do you have documentation on this?
Thans

**Comment by VaultVulp** [comment]
Hello, @manang! Thanks for your interest in my project!

In this case `publisher` is just an abitrary name, as far as I know GitHub validates only the token (aka `password`).

For example, [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry) GitHub suggests to use `USERNAME`.

[This](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-a-registry-using-a-personal-access-token) is the detailed (sort of) explanation about the `${{ secrets.GITHUB_TOKEN }}`and it's relations with the GCR.
