### ISSUE TITLE
build-context does not work

### ISSUE THREAD

**Issue by jalamprea** [VaultVulp/gp-docker-action#21]
I sued to have my Dockerfile in the root of the project, but now I'm organizing my project into subfolders, so I moved the Dockerfile and all my app source into a subfolder `docker-app`.
So on my github action I added the param `build-context: ./docker-app/` but now the CI is not working. I always get an error:

ERROR: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount1250393087/Dockerfile: no such file or directory

**Comment by VaultVulp** [comment]
Hi, @jalamprea !

Thanks for showing interest in my project!

I guessm, there could be an issues with the way I pass custom build args and build context at the same time, I'll try to implement a fix.

**Comment by VaultVulp** [comment]
@jalamprea  Should be fixed now in version 1.5.2
